#pragma once

#include "NativeGameplayTags.h"

namespace KRItemGameplayTags
{
	// ===== Item Types =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equip_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equip_GunModule);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equip_SwordModule);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Equip_Armor);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Consume_Potion);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Consume_Insurance_Coin);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Consume_Insurance_Wallet);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Tool_Light);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Material_Scrap);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Material_Tech);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Material_Doc);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType_Quest);

	// ===== Weapon Stats =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_CritMultiplier);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Sword_CritMultiplier);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Both_AttackSpeed);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_Accuracy);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_Recoil);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Gun_ExtendMag);

	// ===== Ability.Elemental =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Elemental_Fire);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Elemental_Ice);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Elemental_Electronic);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Elemental_Dark);

	// ===== Ability.ApplyCC =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ApplyCC_Stun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ApplyCC_Slow);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ApplyCC_Groggy);

	// ===== Ability.Item =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Item_Stackable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Item_Buyable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Item_Sellable);

	// ===== Ability.Consume =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Consume_Heal);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Consume_Stamina);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Consume_CoreCharge);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Consume_ATKBuff);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Consume_Stealth);

	// ===== Ability.Tool =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Tool_Light);

	// ===== Currency =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Currency_Purchase_Gearing);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Currency_Skill_Corbyte);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Currency_Material);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Currency_Event);

	// ===== Vendor =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Vendor_Official);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Vendor_Black);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Vendor_SoraBell);

	// ===== Stability =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Stability_Normal);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Stability_Caution);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Stability_Emergency);

	// ===== Discount =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Discount);

	// ===== Service =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Service_Enhance);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shop_Service_Repair);

	// ===== Rarity =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Common);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Uncommon);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Rare);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rarity_Epic);
}